name: .NET Build
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    name: build-and-test-windows
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.202
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Build
      run: msbuild /p:Configuration=$env:Configuration -restore
      env:
        Configuration: ${{ matrix.configuration }}
    - name: Upload Scrcpy-GUI
      uses: actions/upload-artifact@v4
      with:
        name: Scrcpy-GUI
        path: bin\Release\scrcpy-gui.exe
