name: .NET Build & Test
on:
  push:
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    name: build-and-test-windows
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # 安装 .NET Core
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 3.1.202
    # 添加 MSBuild.exe 到环境变量: https://github.com/microsoft/setup-msbuild
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    # 编译整个项目
    - name: Build the solution
      run: msbuild /p:Configuration=$env:Configuration -restore
      env:
        Configuration: ${{ matrix.configuration }}
    # 执行单元测试
    - name: Execute unit tests
      run: dotnet test -c $env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}
    - name: Upload Scrcpy-GUI
      uses: actions/upload-artifact@v4
      with:
        name: Scrcpy-GUI
        path: bin\Debug\scrcpy-gui.exe
